components/Duckies/DuckiesHero/index.tsx
components/Duckies/DuckiesHero/styles.scss
config/app.ts
styles/custom.scss

https://openware-inc.atlassian.net/browse/YO-142

fix: update balance details according to figma

---

components/Duckies/DuckiesAffiliates/index.tsx
components/Duckies/DuckiesHero/index.tsx
components/Duckies/DuckiesRedeem/index.tsx
components/Navbar/index.tsx

https://openware-inc.atlassian.net/browse/YO-108

fix(duckies): update duckies page content

---

components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-142

fix: polish head

---

components/Pagination/SimplePagination.tsx

https://openware-inc.atlassian.net/browse/YO-167

feature(duckies): hide prev and next buttons on corresponding pages

---

components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-172

fix: add spinner to modal window

---

components/Duckies/DuckiesEarnMore/index.tsx
components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-174

feat: add copied tooltip

---

components/Duckies/DuckiesEarnMore/index.tsx

https://openware-inc.atlassian.net/browse/YO-135

fix: overflow of hidden link

---

components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-173

[FIX] correct the balance so it doesn't reflex in the current Metamask account.

---

pages/duckies.tsx

https://openware-inc.atlassian.net/browse/YO-116

fix: set relative og image path

---

components/Footer/index.tsx
components/IconExternalLink/index.tsx

https://openware-inc.atlassian.net/browse/YO-182

fix(duckies): update footer + delete unnecessary comments

---

components/Duckies/DuckiesAffiliates/index.tsx

https://openware-inc.atlassian.net/browse/YO-84

fix(duckies): update claim reward function logic DuckiesAffiliates

---

components/Duckies/DuckiesWrapper/index.tsx

https://openware-inc.atlassian.net/browse/YO-201

feature(duckies): dispatch alert on error with connect socials

---

components/Duckies/BountyRow/index.tsx
components/Duckies/DuckiesConnectModalWindow/index.tsx

https://openware-inc.atlassian.net/browse/YO-84

fix(duckies): make claim button unactive after captcha is expired 

---

components/Footer/index.tsx

https://openware-inc.atlassian.net/browse/YO-211

fix(yellow-org): set proper styles for Copyright section

---

components/Duckies/DuckiesEarnMore/index.tsx

https://openware-inc.atlassian.net/browse/YO-208

fix: disable link scrolling

---

components/Duckies/DuckiesFAQ/index.tsx
helpers/HtmlSerializer.tsx

https://openware-inc.atlassian.net/browse/YO-149

fix: polish faq section

---

components/Duckies/AdvancedInput/index.tsx

https://openware-inc.atlassian.net/browse/YO-44

feature(duckies): add AdvancedInput component

---

components/Duckies/BountyRow/index.tsx
components/Duckies/DuckiesAffiliates/index.tsx
components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-84

fix(duckies): reset captcha + positioning

---

components/Duckies/UnloginEyes/index.tsx

https://openware-inc.atlassian.net/browse/YO-223

fix(duckies): propely justify content in bounty table

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-219

fix(duckies): add responsives for DuckiesPrizes

---

components/Duckies/OTPModal/OTPInput.tsx
components/Duckies/OTPModal/PhoneInput.tsx
pages/api/otp/send.ts

https://openware-inc.atlassian.net/browse/YO-31

fix: polish otp modal

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-219

fix(duckies): hide scrollbar + update drop-shadow

---

components/Duckies/DuckiesWrapper/index.tsx
hooks/useSocialConnections.ts

https://openware-inc.atlassian.net/browse/YO-192

feat: add improved social connections

---

components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-184

fix: polish mobile status duck

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-219

fix(duckies): shadow for DuckiesPrizes

---

components/Duckies/DuckiesAffiliates/index.tsx
components/Duckies/DuckiesEarnMore/index.tsx
components/Duckies/DuckiesFAQ/index.tsx
components/Duckies/DuckiesHero/index.tsx
components/Duckies/DuckiesRedeem/index.tsx

https://openware-inc.atlassian.net/browse/YO-108

fix(duckies): update page content

---

components/Duckies/OTPModal/index.tsx
hooks/useBounties.ts
hooks/useSocialConnections.ts
pages/api/otp/fetchPhoneNumber.ts
pages/api/otp/isPhoneVerified.ts
pages/api/socials/saveAddress.ts
pages/api/socials/saveEmail.ts

https://openware-inc.atlassian.net/browse/YO-229

fix: move supbase calls to api

---

pages/_document.tsx

https://openware-inc.atlassian.net/browse/YO-225

fix(yellow-org): hide scrollbar on page scroll

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-219

fix(duckies): scale DuckiesPrizes cards dependent on screen size

---

components/Duckies/DuckiesWrapper/index.tsx

https://openware-inc.atlassian.net/browse/YO-250

fix(duckies): add missing deps for DuckiesWrapper

---

components/Duckies/Modals/ClaimRewardModal/index.tsx
hooks/useBounties.ts

https://openware-inc.atlassian.net/browse/YO-93

fix: show alert on second referral claim

---

hooks/useAffiliates.ts
hooks/useBounties.ts

https://openware-inc.atlassian.net/browse/YO-249

fix: set quests to default on logout

---

components/Duckies/DuckiesHero/index.tsx
hooks/useBounties.ts
hooks/useDuckiesBalance.ts

https://openware-inc.atlassian.net/browse/YO-248

fix: update balance on claims without reload

---

pages/api/otp/send.ts

https://openware-inc.atlassian.net/browse/YO-251

fix: allow otp for several unverified phone numbers

---

pages/api/otp/fetchPhoneNumber.ts
pages/api/otp/send.ts

https://openware-inc.atlassian.net/browse/YO-252

fix: prevents phone api vulnerabilities

---

components/Navbar/navItems.js

https://openware-inc.atlassian.net/browse/YO-218

fix(yellow-org): add Duckies tab to navbar

---

components/Duckies/Modals/ClaimRewardModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-269

fix(duckies): update claim reward modal content

---

components/Duckies/BountyRow/index.tsx
components/Duckies/Modals/ClaimRewardModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-268

fix(duckies): update tx in-progress content

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-272

fix(duckies): upgrade responsiveness for DuckiesPrizes

---

components/Duckies/DuckiesPrizes/index.tsx

https://openware-inc.atlassian.net/browse/YO-279

fix(duckies): deprecate gyroscope support for cards

---

components/Duckies/OTPModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-232

fix: rerender otp modal after account change

---

components/Navbar/navItems.js

https://openware-inc.atlassian.net/browse/YO-218

fix(yellow-org): delete Duckies from navbar

---

components/Duckies/DuckiesWrapper/index.tsx
components/Duckies/OTPModal/PhoneInput.tsx
components/Duckies/OTPModal/index.tsx
helpers/withDuckiesSession.ts
hooks/useBounties.ts
hooks/useSocialConnections.ts
pages/api/otp/fetchPhoneNumber.ts
pages/api/otp/isPhoneVerified.ts
pages/api/otp/send.ts
pages/api/otp/verify.ts
pages/api/socials/saveAddress.ts
pages/api/socials/saveEmail.ts
pages/api/users/me.ts

https://openware-inc.atlassian.net/browse/YO-229

fix: secure api endpoints from external access

---

components/Duckies/DuckiesEarnMore/index.tsx
components/Duckies/DuckiesPrizes/index.tsx
components/Duckies/DuckiesWrapper/index.tsx

https://openware-inc.atlassian.net/browse/YO-273

fix: remove window artefacts

---

components/Duckies/DuckiesFAQ/index.tsx

https://openware-inc.atlassian.net/browse/YO-265

fix: polish faq scroll ux

---

components/Duckies/Modals/ClaimRewardModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-255

fix(duckies): display processing modal on Claim All

---

components/Duckies/BountyRow/index.tsx
components/Duckies/Captcha/index.tsx
components/Duckies/Modals/ClaimRewardModal/index.tsx
hooks/useBounties.ts

https://openware-inc.atlassian.net/browse/YO-228

fix: move captcha to separate component

---

components/Duckies/OTPModal/PhoneInput.tsx
components/Duckies/OTPModal/index.tsx
config/app.ts
pages/api/otp/send.ts
pages/api/otp/verify.ts

https://openware-inc.atlassian.net/browse/YO-231

feat: add backend delays for otp sending and verifying

---

hooks/useMetaMask.ts

https://openware-inc.atlassian.net/browse/YO-284

fix: redirect to store on mobile when metamask is not installed

---

components/Duckies/BountyRow/index.tsx
components/Duckies/Captcha/index.tsx
components/Duckies/Modals/ClaimRewardModal/index.tsx
components/Duckies/OTPModal/OTPInput.tsx
components/Duckies/OTPModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-285
https://openware-inc.atlassian.net/browse/YO-231

fix: polish otp input and captcha

---

components/Duckies/Modals/ClaimRewardModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-267

fix: add success screen after claiming rewards

---

hooks/useMetaMask.ts

https://openware-inc.atlassian.net/browse/YO-283

fix: mobile metamask adding network flow

---

components/Duckies/BountyRow/index.tsx
components/Duckies/OTPModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-271

fix(duckies): otp success content

---

components/Duckies/OTPModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-285

fix: disabled otp submit on change of code

---

components/Duckies/Modals/ClaimRewardModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-267

fix: polish success claim window

---

components/Duckies/Modals/ClaimRewardModal/index.tsx
hooks/useBounties.ts

https://openware-inc.atlassian.net/browse/YO-270

fix(duckies): update claim reward content

---

components/Duckies/BountyRow/index.tsx
components/Duckies/Modals/SocialAuthModal/index.tsx

https://openware-inc.atlassian.net/browse/YO-295

fix: change connect social modal image

---

components/Duckies/DuckiesHero/index.tsx

https://openware-inc.atlassian.net/browse/YO-290

fix: update info section in balance circle
